const crosswordsData = [
  { id:1, title:'Кроссворд #1', difficulty:1,
    grid:[
      ['.','1',' ',' ',' ','.'],
      ['2',' ','.','3',' ',' '],
      [' ',' ','4',' ',' ',' '],
      ['.','5',' ',' ','.','.'],
      ['6',' ','.','.','7',' '],
      [' ','.','.','8',' ',' '],
    ],
    words:[
      {number:1,direction:'across',row:0,col:1,length:4,clue:'Жёлтый кислый цитрус',answer:'ЛИМО'},
      {number:2,direction:'across',row:1,col:0,length:2,clue:'Нота выше «до»',answer:'РЕ'},
      {number:3,direction:'across',row:1,col:3,length:3,clue:'Кот — домашний …',answer:'КОТ'},
      {number:4,direction:'across',row:2,col:2,length:4,clue:'Предмет для письма',answer:'РУЧК'},
      {number:5,direction:'across',row:3,col:1,length:3,clue:'Хвойный лес',answer:'БОР'},
      {number:6,direction:'across',row:4,col:0,length:2,clue:'Мамин брат',answer:'ДЯД'},
      {number:7,direction:'down',row:4,col:5,length:2,clue:'Крылья есть, летать не может',answer:'ЭМ'},
      {number:8,direction:'across',row:5,col:3,length:3,clue:'Тихий отдых ночью',answer:'СОН'},
    ]
  },
  { id:2, title:'Кроссворд #2', difficulty:1,
    grid:[
      ['1',' ',' ','.','.'],
      [' ','.','2',' ',' '],
      [' ',' ',' ','.','3'],
      ['.','4',' ',' ',' '],
      ['5',' ','.','6',' '],
    ],
    words:[
      {number:1,direction:'across',row:0,col:0,length:3,clue:'Хищная речная рыба',answer:'СОМ'},
      {number:2,direction:'across',row:1,col:2,length:3,clue:'Фрукт-символ мира',answer:'ЯБЛ'},
      {number:3,direction:'down',row:2,col:4,length:3,clue:'Летний горячий период',answer:'ЗНО'},
      {number:4,direction:'across',row:3,col:1,length:4,clue:'Тёплое время года',answer:'ЛЕТО'},
      {number:5,direction:'across',row:4,col:0,length:2,clue:'Орган обоняния',answer:'НОС'},
      {number:6,direction:'across',row:4,col:3,length:2,clue:'Вкусный фруктовый напиток',answer:'СОК'},
    ]
  },
  { id:3, title:'Кроссворд #3', difficulty:1,
    grid:[
      ['1',' ',' ','.','.'],
      [' ','.','2',' ',' '],
      ['3',' ',' ',' ','.'],
      ['.','.','.','4',' '],
      ['.','5',' ',' ',' '],
    ],
    words:[
      {number:1,direction:'across',row:0,col:0,length:3,clue:'Небо ночью усыпано …',answer:'ЗВЕ'},
      {number:2,direction:'across',row:1,col:2,length:3,clue:'Детская игрушка-юла',answer:'ЮЛА'},
      {number:3,direction:'across',row:2,col:0,length:4,clue:'Время дождей и листопада',answer:'ОСЕН'},
      {number:4,direction:'across',row:3,col:3,length:2,clue:'Нота после «ля»',answer:'СИ'},
      {number:5,direction:'across',row:4,col:1,length:4,clue:'Комната для сна',answer:'СПАЛ'},
    ]
  },
  { id:4, title:'Кроссворд #4', difficulty:2,
    grid:[
      ['1',' ',' ',' ','.','2',' ',' '],
      [' ','.','3',' ',' ',' ',' ',' '],
      [' ',' ',' ','.','4',' ',' ',' '],
      ['.','5',' ',' ',' ',' ','.','.'],
      ['6',' ','.','.','7',' ',' ',' '],
      [' ',' ',' ','8',' ',' ',' ','.'],
    ],
    words:[
      {number:1,direction:'across',row:0,col:0,length:4,clue:'Морское судно',answer:'КОРБ'},
      {number:2,direction:'across',row:0,col:5,length:3,clue:'Дерево с шишками',answer:'ЕЛЬ'},
      {number:3,direction:'across',row:1,col:2,length:6,clue:'Природный источник воды',answer:'КЛЮЧИК'},
      {number:4,direction:'across',row:2,col:4,length:4,clue:'Пустынное колючее растение',answer:'КАК'},
      {number:5,direction:'across',row:3,col:1,length:5,clue:'Струнный инструмент',answer:'ВИОЛА'},
      {number:6,direction:'across',row:4,col:0,length:2,clue:'Серый великан с хоботом',answer:'СЛ'},
      {number:7,direction:'across',row:4,col:4,length:4,clue:'Белые осадки зимой',answer:'СНЕГ'},
      {number:8,direction:'across',row:5,col:3,length:4,clue:'Инструмент художника',answer:'КРАС'},
    ]
  },
  { id:5, title:'Кроссворд #5', difficulty:2,
    grid:[
      ['.','1',' ',' ',' ',' ','.'],
      ['2',' ','.','.','3',' ',' '],
      [' ','.','.','4',' ',' ',' '],
      ['5',' ',' ',' ',' ','.','.'],
      [' ','.','6',' ',' ',' ','.'],
      ['7',' ',' ',' ','.','.','.'],
    ],
    words:[
      {number:1,direction:'across',row:0,col:1,length:5,clue:'Мебель для сна',answer:'КРОВА'},
      {number:2,direction:'across',row:1,col:0,length:2,clue:'Оружие лучника',answer:'ЛУК'},
      {number:3,direction:'across',row:1,col:4,length:3,clue:'Зелёный овощ на грядке',answer:'ЛУК'},
      {number:4,direction:'across',row:2,col:3,length:4,clue:'Государственный флаг',answer:'ЗНАМ'},
      {number:5,direction:'across',row:3,col:0,length:5,clue:'Рыночная площадь',answer:'РЫНОК'},
      {number:6,direction:'across',row:4,col:2,length:4,clue:'Лесная алая ягода',answer:'МАЛИ'},
      {number:7,direction:'across',row:5,col:0,length:4,clue:'Крупный лесной кабан',answer:'КАБА'},
    ]
  },
  { id:6, title:'Кроссворд #6', difficulty:2,
    grid:[
      ['1',' ',' ',' ',' ','.'],
      [' ','.','2',' ',' ',' '],
      [' ','.','.','3',' ',' '],
      ['.','4',' ',' ',' ','.'],
      ['5',' ','.','.','6',' '],
      [' ','.','.','7',' ',' '],
    ],
    words:[
      {number:1,direction:'across',row:0,col:0,length:5,clue:'Быстрый горный поток',answer:'ПОТОК'},
      {number:2,direction:'across',row:1,col:2,length:4,clue:'Осьминог живёт в …',answer:'МОРЕ'},
      {number:3,direction:'across',row:2,col:3,length:3,clue:'Зимние длинные лыжи',answer:'ЛЫЖ'},
      {number:4,direction:'across',row:3,col:1,length:4,clue:'Ночная мудрая птица',answer:'СОВА'},
      {number:5,direction:'across',row:4,col:0,length:2,clue:'Мамина мама',answer:'БА'},
      {number:6,direction:'down',row:4,col:5,length:2,clue:'Чай с этой травой',answer:'МЯТ'},
      {number:7,direction:'across',row:5,col:3,length:3,clue:'Речной полосатый хищник',answer:'ОКУ'},
    ]
  },
  { id:7, title:'Кроссворд #7', difficulty:3,
    grid:[
      ['1',' ',' ',' ',' ',' ','.','2',' '],
      [' ','.','3',' ',' ',' ',' ',' ','.'],
      [' ',' ',' ','.','4',' ',' ',' ',' '],
      ['.','.','5',' ',' ',' ',' ','.','.'],
      ['6',' ',' ','.','.','7',' ',' ',' '],
      [' ',' ','.','8',' ',' ',' ',' ','.'],
      ['.','9',' ',' ',' ',' ','.','.','.'],
      ['10',' ',' ',' ','.','11',' ',' ',' '],
    ],
    words:[
      {number:1,direction:'across',row:0,col:0,length:6,clue:'Посуда для варки супа',answer:'КАСТРЯ'},
      {number:2,direction:'across',row:0,col:7,length:2,clue:'Тропический попугай',answer:'АРА'},
      {number:3,direction:'across',row:1,col:2,length:6,clue:'Дикие дебри тропиков',answer:'ДЖУНГЛ'},
      {number:4,direction:'across',row:2,col:4,length:5,clue:'Земля — третья … от Солнца',answer:'ПЛАНЕ'},
      {number:5,direction:'across',row:3,col:2,length:5,clue:'Крупное строение из кирпича',answer:'ЗДАНИ'},
      {number:6,direction:'across',row:4,col:0,length:3,clue:'Высокая дозорная постройка',answer:'ЗАМ'},
      {number:7,direction:'across',row:4,col:5,length:4,clue:'Полосатое животное саванны',answer:'ЗЕБР'},
      {number:8,direction:'across',row:5,col:3,length:5,clue:'Торжественная патриотическая песня',answer:'ГИМН'},
      {number:9,direction:'across',row:6,col:1,length:5,clue:'Дерево с белым стволом',answer:'БЕРЁЗ'},
      {number:10,direction:'across',row:7,col:0,length:4,clue:'Зимний вид спорта на горе',answer:'ЛЫЖИ'},
      {number:11,direction:'across',row:7,col:5,length:4,clue:'Радужный природный камень',answer:'ОПАЛ'},
    ]
  },
  { id:8, title:'Кроссворд #8', difficulty:3,
    grid:[
      ['.','1',' ',' ',' ',' ',' ','.','.'],
      ['2',' ',' ','.','.','3',' ',' ',' '],
      [' ','.','.','4',' ',' ',' ',' ','.'],
      ['5',' ',' ',' ',' ','.','6',' ',' '],
      [' ','.','7',' ',' ',' ','.',' ','.'],
      ['8',' ',' ',' ','.','9',' ',' ',' '],
      ['.','.','10',' ',' ',' ',' ','.','.'],
      ['11',' ',' ',' ',' ','.','12',' ',' '],
    ],
    words:[
      {number:1,direction:'across',row:0,col:1,length:6,clue:'Наука о строении тела',answer:'АНАТОМ'},
      {number:2,direction:'across',row:1,col:0,length:3,clue:'Хищная птица-охотник',answer:'ЯСТ'},
      {number:3,direction:'across',row:1,col:5,length:4,clue:'Ядовитая очковая змея',answer:'КОБР'},
      {number:4,direction:'across',row:2,col:3,length:5,clue:'Зал с картинами',answer:'ГАЛЕР'},
      {number:5,direction:'across',row:3,col:0,length:5,clue:'Страна восходящего солнца',answer:'ЯПОНИ'},
      {number:6,direction:'across',row:3,col:6,length:3,clue:'Цвет ясного неба',answer:'СИН'},
      {number:7,direction:'across',row:4,col:2,length:4,clue:'Тёмная вулканическая порода',answer:'БАЗЛ'},
      {number:8,direction:'across',row:5,col:0,length:4,clue:'Стул без спинки',answer:'ТАБУ'},
      {number:9,direction:'across',row:5,col:5,length:4,clue:'Металлический крюк корабля',answer:'ЯКОР'},
      {number:10,direction:'across',row:6,col:2,length:5,clue:'Сладкий тропический плод',answer:'МАНГО'},
      {number:11,direction:'across',row:7,col:0,length:5,clue:'Яркий праздник-шествие',answer:'КАРНА'},
      {number:12,direction:'across',row:7,col:6,length:3,clue:'Зерно для плова',answer:'РИС'},
    ]
  },
  { id:9, title:'Кроссворд #9', difficulty:3,
    grid:[
      ['1',' ',' ',' ',' ','.','2',' ',' '],
      [' ','.','3',' ',' ',' ',' ',' ','.'],
      [' ',' ',' ','.','4',' ',' ',' ',' '],
      ['.','5',' ',' ',' ',' ','.','6',' '],
      ['7',' ',' ','.','.','8',' ',' ',' '],
      [' ',' ','.','9',' ',' ',' ','.','.'],
      ['.','.','10',' ',' ',' ',' ',' ','.'],
      ['11',' ',' ',' ','.','12',' ',' ',' '],
    ],
    words:[
      {number:1,direction:'across',row:0,col:0,length:5,clue:'Самый быстрый сухопутный хищник',answer:'ГЕПАР'},
      {number:2,direction:'across',row:0,col:6,length:3,clue:'Утренняя тёплая … из круп',answer:'КАШ'},
      {number:3,direction:'across',row:1,col:2,length:6,clue:'Учёный, изучающий звёзды',answer:'АСТРО'},
      {number:4,direction:'across',row:2,col:4,length:5,clue:'Чертёжный инструмент',answer:'ЛИНЕЙ'},
      {number:5,direction:'across',row:3,col:1,length:5,clue:'Пространство за атмосферой',answer:'КОСМО'},
      {number:6,direction:'down',row:3,col:7,length:3,clue:'Твёрдый лесной плод',answer:'ОРЕ'},
      {number:7,direction:'across',row:4,col:0,length:3,clue:'Вагон на рельсах',answer:'ВАГ'},
      {number:8,direction:'across',row:4,col:5,length:4,clue:'Домашняя птица несущая яйца',answer:'КУРИ'},
      {number:9,direction:'across',row:5,col:3,length:4,clue:'Персонаж сказок — Иван …',answer:'ЦАРЕ'},
      {number:10,direction:'across',row:6,col:2,length:6,clue:'Горная цепь',answer:'ХРЕБЕТ'},
      {number:11,direction:'across',row:7,col:0,length:4,clue:'Иглокожее морское животное',answer:'МОРСК'},
      {number:12,direction:'across',row:7,col:5,length:4,clue:'Бабочка до превращения',answer:'МОТЫЛ'},
    ]
  },
  { id:10, title:'Кроссворд #10', difficulty:3,
    grid:[
      ['.','1',' ',' ',' ',' ',' ','.'],
      ['2',' ','.','.','3',' ',' ',' '],
      [' ','.','.','4',' ',' ',' ','.'],
      ['5',' ',' ',' ',' ','.','6',' '],
      [' ','.','7',' ',' ',' ','.',' '],
      ['8',' ',' ',' ','.','9',' ',' '],
      ['.','.','10',' ',' ',' ',' ','.'],
      ['11',' ',' ',' ',' ','.','.','.'],
    ],
    words:[
      {number:1,direction:'across',row:0,col:1,length:6,clue:'Искусство движущихся картин',answer:'КИНЕМА'},
      {number:2,direction:'across',row:1,col:0,length:2,clue:'«Бе» — вторая буква алфавита',answer:'БЕ'},
      {number:3,direction:'across',row:1,col:4,length:4,clue:'Блестящая гладкая ткань',answer:'ШЁЛК'},
      {number:4,direction:'across',row:2,col:3,length:4,clue:'Лопасть вращающегося колеса',answer:'ЛОПА'},
      {number:5,direction:'across',row:3,col:0,length:5,clue:'Короткая запись в дневнике',answer:'ЗАМЕТ'},
      {number:6,direction:'down',row:3,col:6,length:4,clue:'Первый хрупкий лёд',answer:'ИНЕЙ'},
      {number:7,direction:'across',row:4,col:2,length:4,clue:'Ценная бумага компании',answer:'АКЦИ'},
      {number:8,direction:'across',row:5,col:0,length:4,clue:'Птица-барабанщик леса',answer:'ДЯТЛ'},
      {number:9,direction:'across',row:5,col:5,length:3,clue:'Заряженная частица атома',answer:'ИОН'},
      {number:10,direction:'across',row:6,col:2,length:5,clue:'Подземный городской транспорт',answer:'МЕТРО'},
      {number:11,direction:'across',row:7,col:0,length:5,clue:'Высшая горная точка',answer:'ПИКЕТ'},
    ]
  },
];